/**
 * Defines for RFM9XW
 *
 * @author Aaron Chan
 */
#ifndef RFM9XW_DEFS_H
#define RFM9XW_DEFS_H

namespace RFM9XW_DEFS {

    typedef enum {
        FSK_OOK_MODE = 0,
        LORA_MODE = 1
    } RFM9XW_OPERATING_MODE_T;

    typedef enum {
        RFM9XW_REG_FIFO_ACCESS = 0x00,
        RFM9XW_REG_OP_MODE = 0x01,
        RFM9XW_REG_FR_MSB = 0x06,
        RFM9XW_REG_FR_MID = 0x07,
        RFM9XW_REG_FR_LSB = 0x08,
        RFM9XW_REG_PA_CONFIG = 0x09,
        RFM9XW_REG_LNA = 0x0C,
        RFM9XW_REG_FIFO_ADDR_PTR = 0x0D,
        RFM9XW_REG_FIFO_TX_BASE_ADDR = 0x0E,
        RFM9XW_REG_FIFO_RX_BASE_ADDR = 0x0F,
        RFM9XW_REG_FIFO_RX_CURRENT_ADDR = 0x10,
        RFM9XW_REG_IRQ_FLAGS = 0x12,
        RFM9XW_REG_FIFO_RX_BYTES_NB = 0x13,
        RFM9XW_REG_PACKET_SNR = 0x19,
        RFM9XW_REG_MODEM_CONFIG_1 = 0x1D,
        RFM9XW_REG_MODEM_CONFIG_2 = 0x1E,
        RFM9XW_REG_SYMB_TIMEOUT_LSB = 0x1F,
        RFM9XW_REG_PREAMBLE_MSB = 0x20,
        RFM9XW_REG_PREAMBLE_LSB = 0x21,
        RFM9XW_REG_PAYLOAD_LENGTH = 0x22,
        RFM9XW_REG_MAX_PAYLOAD_LENGTH = 0x23,
        RFM9XW_REG_MODEM_CONFIG_3 = 0x26,
        RFM9XW_REG_PACKET_CONFIG_1 = 0x30,
        RFM9XW_REG_PACKET_CONFIG_2 = 0x31,
        RFM9XW_REG_INVERT_IQ_1 = 0x33,
        RFM9XW_REG_DETECTION_THRESHOLD = 0x37,
        RFM9XW_REG_SYNC_WORD = 0x39,
        RFM9XW_REG_INVERT_IQ_2 = 0x3B,
        RFM9XW_REG_DIO_MAPPING_1 = 0x40,
        RFM9XW_REG_DIO_MAPPING_2 = 0x41,
        RFM9XW_REG_VERSION = 0x42,
        RFM9XW_REG_PA_DAC = 0x4D
    } RFM9XW_REGISTER_T;

    typedef enum {
        COMMON_REG_FIFO = 0x00,
        COMMON_REG_OP_MODE = 0x01,

        COMMON_REG_FRF_MSB = 0x06,
        COMMON_REG_FRF_MID = 0x07,
        COMMON_REG_FRF_LSB = 0x08,

        COMMON_REG_PA_CONFIG = 0x09,
        COMMON_REG_PA_RAMP = 0x0A,
        COMMON_REG_OCP = 0x0B,
        COMMON_REG_LNA = 0x0C,

        COMMON_REG_DIO_MAPPING_1 = 0x40,
        COMMON_REG_DIO_MAPPING_2 = 0x41,
        COMMON_REG_VERSION = 0x42,

        COMMON_REG_TCXO = 0x4B,
        COMMON_REG_PA_DAC = 0x4D,
        COMMON_REG_FORMER_TEMP = 0x5B,
        COMMON_REG_AGC_REF = 0x61,

        COMMON_REG_AGC_THRESH_1 = 0x62,
        COMMON_REG_AGC_THRESH_2 = 0x63,
        COMMON_REG_AGC_THRESH_3 = 0x64,

        COMMON_REG_PLL = 0x70,
        COMMON_REG_TEST = 0x71
    } RFM9XW_COMMON_REGISTER_T;

    typedef enum {
        LORA_REG_FIFO_ADDR_PTR = 0x0D,
        LORA_REG_FIFO_TX_BASE_ADDR = 0x0E,
        LORA_REG_FIFO_RX_BASE_ADDR = 0x0F,
        LORA_REG_FIFO_RX_CURRENT_ADDR = 0x10,

        LORA_REG_IRQ_FLAGS_MASK = 0x11,
        LORA_REG_IRQ_FLAGS = 0x12,

        LORA_REG_RX_NB_BYTES = 0x13,
        LORA_REG_RX_HEADER_CNT_VALUE_MSB = 0x14,
        LORA_REG_RX_HEADER_CNT_VALUE_LSB = 0x15,
        LORA_REG_RX_PACKET_CNT_VALUE_MSB = 0x16,
        LORA_REG_RX_PACKET_CNT_VALUE_LSB = 0x17,

        LORA_REG_MODEM_STAT = 0x18,

        LORA_REG_PKT_SNR_VALUE = 0x19,
        LORA_REG_PKT_RSSI_VALUE = 0x1A,

        LORA_REG_RSSI_VALUE = 0x1B,

        LORA_REG_HOP_CHANNEL = 0x1C,

        LORA_REG_MODEM_CONFIG_1 = 0x1D,
        LORA_REG_MODEM_CONFIG_2 = 0x1E,

        LORA_REG_SYMB_TIMEOUT_LSB = 0x1F,

        LORA_REG_PREAMBLE_MSB = 0x20,
        LORA_REG_PREAMBLE_LSB = 0x21,

        LORA_REG_PAYLOAD_LENGTH = 0x22,
        LORA_REG_MAX_PAYLOAD_LENGTH = 0x23,

        LORA_REG_HOP_PERIOD = 0x24,
        LORA_REG_FIFO_RX_BYTE_ADDR = 0x25,
        LORA_REG_MODEM_CONFIG_3 = 0x26,

        LORA_REG_FEI_MSB = 0x28,
        LORA_REG_FEI_MID = 0x29,
        LORA_REG_FEI_LSB = 0x2A,

        LORA_REG_RSSI_WIDEBAND = 0x2C,

        LORA_REG_IF_FREQ_1 = 0x2F,
        LORA_REG_IF_FREQ_2 = 0x30,

        LORA_REG_DETECT_OPTIMIZE = 0x31,

        LORA_REG_INVERT_IQ = 0x33,

        LORA_REG_HIGH_BW_OPTIMIZE_1 = 0x36,
        LORA_REG_DETECTION_THRESHOLD = 0x37,

        LORA_REG_SYNC_WORD = 0x39,

        LORA_REG_HIGH_BW_OPTIMIZE_2 = 0x3A,
        LORA_REG_INVERT_IQ_2 = 0x3B,
    } RFM9XW_LORA_REGISTER_T;

    typedef enum {
        RFM9XW_MODE_SLEEP = 0x00,
        RFM9XW_MODE_LORA_SLEEP = 0x80,
        RFM9XW_MODE_STANDBY = 0x81,
        RFM9XW_MODE_TX = 0x83,
        RFM9XW_MODE_RX_SINGLE = 0x86
    } RFM9XW_MODE_T;

    typedef enum {
        REG_OP_MODE_SLEEP = 0b000,
        REG_OP_MODE_STANDBY = 0b001,
        REG_OP_MODE_FSTx = 0b010,
        REG_OP_MODE_Tx = 0b011,
        REG_OP_MODE_FSRx = 0b100,
        REG_OP_MODE_CONT_Rx = 0b101,
    } RFM9XW_REG_OP_MODE_T;

    typedef enum {
        RFM9XW_RX_MODE_NONE = 0,
        RFM9XW_RX_MODE_1 = 1,
        RFM9XW_RX_MODE_1_2 = 2
    } RFM9XW_RX_MODE_T;

    typedef enum {
        RFM9XW_INT_DIO0,
        RFM9XW_INT_DIO1,
        RFM9XW_INT_DIO5,
    } RFM9XW_INT_T;


    // Refer to table 28 and 29 in datasheet
    typedef enum {
        DIO_ZERO_PAY_RDY_PKT_SNT = 0b00,
        DIO_ZERO_CRC_OK = 0b01,
        DIO_ZERO_NO_OP = 0b10,
        DIO_ZERO_TEMP_CHG_LOW_BATT = 0b11,
    } PACKET_DIO_ZERO_MAPPING_T;

    typedef enum {
        DIO_ONE_FIFO_LEVEL = 0b00,
        DIO_ONE_FIFO_EMPTY = 0b01,
        DIO_ONE_FIFO_FULL = 0b10,
        DIO_ONE_NO_OP = 0b11,
    } PACKET_DIO_ONE_MAPPING_T;

    typedef enum {
        DIO_TWO_FIFO_FULL = 0b00,
        DIO_TWO_RX_RDY = 0b01,
        DIO_TWO_FIFO_FULL_TIME_OUT = 0b10,
        DIO_TWO_FIFO_FULL_SYNC_ADDR = 0b11,
    } PACKET_DIO_TWO_MAPPING_T;

    typedef enum {
        DIO_THREE_FIFO_EMPTY = 0b00, // Can also be 0b10 and 0b11
        DIO_THREE_TX_READY = 0b01,
    } PACKET_DIO_THREE_MAPPING_T;

    typedef enum {
        DIO_FOUR_TEMP_CHG_LOW_BATT = 0b00,
        DIO_FOUR_PLL_LOCK = 0b01,
        DIO_FOUR_RX_TIME_OUT = 0b10,
        DIO_FOUR_PREAMBLE_DETECT = 0b11,
    } PACKET_DIO_FOUR_MAPPING_T;

    typedef enum {
        DIO_FIVE_CLK_OUT = 0b00,
        DIO_FIVE_PLL_LOCK = 0b01,
        DIO_FIVE_DATA = 0b10,
        DIO_FIVE_MODE_READY = 0b11,
    } PACKET_DIO_FIVE_MAPPING_T;
}

#endif // RFM9XW_DEFS_H
